import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Zain,
  Lora,
  Plus_Jakarta_Sans,
} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const zain = Zain({
  weight: "800",
  variable: "--font-zain",
  subsets: ["latin"],
});

const pjs = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${zain.variable} ${pjs.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
